### ISSUE TITLE
script no longer working

### ISSUE THREAD

**Issue by shape55** [rossy/youtube-video-download#16]
hi, firstly, your contact links are not working here: http://rossy2401.github.io/youtube-video-download/#contact - click and nothing happens. no info shown under 'contact'

this script has been broken for ages, in both safari and firefox. i stopped using it on safari last year and just tried it on firefox, yet it no longer works there either.  this problem is happening:  "There's no Download button, or when I click on the Download button there's no menu." - there is a download button but the menu opens into a tiny rectangle the width of about 2 mouse pointers, so no links can displayed or clicked. same exact problem on safari.

it's really too bad as this was hands down the best youtube video download script i have ever used.

**Comment by shape55** [comment]
ok, just tried this fix and it works! https://github.com/rossy2401/youtube-video-download/issues/9

it would be very helpful to post this fix on your github page: http://rossy2401.github.io/youtube-video-download, or better yet an updated/alternate script version, as most users won't go this far in seeking a solution.

**Comment by rossy** [comment]
Yeah, I guess I've been neglecting this project. As you noticed, the website was never finished. I've been meaning to pick it back up again, but I can't promise anything, especially since I have uni exams at the moment.

I'll see if I can apply that fix though.
