### ISSUE TITLE
'Title format' field width

### ISSUE THREAD

**Issue by S-ed** [rossy/youtube-video-download#3]
Title format field in Options is wider than window. That cause crop and bottom scrollbar appearance.
Firefox 16.0.2 (seems ok under Opera 12.10)

**Comment by rossy** [comment]
Whoops, forgot a vendor prefix.

**Comment by S-ed** [comment]
Now it's ok. Oh, btw, i think it's best script i've seen.(i'm using it already year or more) Thanks. =)
