### ISSUE TITLE
FIX - HTML5 Player Downloading

### ISSUE THREAD

**Issue by rarspace01** [rossy/youtube-video-download#9]
If you're using the html5 player, and can't download anything - when you click the arrow, the box is blank - do the following to fix your script:

Using Find & Replace, search for yt.playerConfig.args, and replace it with ytplayer.config.args.

If you're using version 3.2.\* of the script, also search for getHTML5Map();, and replace it with //getHTML5Map();.

**Comment by shape55** [comment]
this worked!!  thank you!! had this script disabled since like a year ago and really missed it.

**Comment by rossy** [comment]
Thanks for the fix. I guess I've been neglecting this project. I want to do some more work on at some point, but this should get it working again.

**Comment by shape55** [comment]
ok cool. i updated to 4.1.2 and i can confirm it works on the latest firefox.  

did your script ever allow downloading as audio only? i could have sworn it did but don't see those options now.  maybe it was another script or safari extension, as i was using safari before.  i tried out this add-on for firefox: https://addons.mozilla.org/en-US/firefox/addon/easy-youtube-video-download/?src=ss which provides options for audio formats.

**Comment by rossy** [comment]
Glad it works!

> did your script ever allow downloading as audio only?

This script never did. Some other scripts used external websites to convert the video to MP3, but mine only worked with the formats provided by YouTube itself, which at the time didn't include any audio-only formats (though these days, I think DASH provides audio-only streams.)

**Comment by SWalkerTTU** [comment]
The script now only seems to allow 720p at best, even where 1080p or higher is available. It looks like YT changed something again.
